export const carData = [
  {
    id: 1,
    title: "GMC Acadia",
    description: "The truck and SUV division of General Motors, GMC’s most popular models include the Sierra pickup and Yukon SUV.",
    image: "https://i.ibb.co/sK310Vr/gmc-acadia-review-specs-pricing-features-videos-and-more.webp",
    price: 45000,
    totalRun: 265478, 
    fuelType: "Diesel",
    transmissionType: "Semi-Automatic",
    sellerName: "Dev 7",
    sellerPhone: "246 4572 7541",
    sellerPhoto: "https://i.ibb.co/DWJy4Y9/3.png"
  },
  {
    id: 2,
    title: "Jeep Wrangler (TJ)",
    description: "This car is pure love. I drove it pure love and care. It is in fresh condition.",
    image: "https://i.ibb.co/SBGTKj1/gos9stqvlcq71.jpg",
    price: 35000,
    totalRun: 335478,
    fuelType: "Diesel",
    transmissionType: "Manual",
    sellerName: "Dev 7",
    sellerPhone: "246 57471 7541",
    sellerPhoto: "https://i.ibb.co/DWJy4Y9/3.png"
  },
  {
    id: 3,
    title: "Ferrari SF90 Stradale",
    description: "The car is in very good condition. You can have a physical check and test drive.",
    image: "https://i.ibb.co/kXPLqMM/front-left-side-47.webp",
    price: 19000,
    totalRun: 1357,
    fuelType: "Hybrid",
    transmissionType: "Automatic",
    sellerName: "New user",
    sellerPhone: "246 57471 55669",
    sellerPhoto: "https://i.ibb.co/g4YtpzM/3.png"
  },
  {
    id: 4,
    title: "RX",
    description: "Lexus RX is a luxury SUV with a striking design and a plush interior.",
    image: "https://i.ibb.co/T03F820/001-2024-Lexus-RX-350-front-view.jpg",
    price: 9000,
    totalRun: 45515,
    fuelType: "Diesel",
    transmissionType: "Manual",
    sellerName: "John Obi",
    sellerPhone: "+1 (103) 309-9692",
    sellerPhoto: "https://i.ibb.co/Z6ThdTY/Bechtel-Profile-Square.jpg"
  },
  {
    id: 5,
    title: "XC90",
    description: "Volvo's XC90 is a luxury SUV that prioritizes safety and comfort.",
    image: "https://i.ibb.co/vvgrwxJ/2024-volvo-xc90-101-649311ffdc60b.jpg",
    price: 7800,
    totalRun: 556547,
    fuelType: "Diesel",
    transmissionType: "Automatic",
    sellerName: "John Obi",
    sellerPhone: "+1 (718) 437-9372",
    sellerPhoto: "https://i.ibb.co/Z6ThdTY/Bechtel-Profile-Square.jpg"
  },
  {
    id: 6,
    title: "Chevrolet Corvette",
    description: "The 2023 Chevrolet Corvette redefines performance with its sleek design and powerful V8 engine.",
    image: "https://i.ibb.co/HXzPwtK/2023-chevrolet-corvette-z06-14.jpg",
    price: 10000,
    totalRun: 78864,
    fuelType: "Gasoline",
    transmissionType: "Automatic",
    sellerName: "Sakibbai",
    sellerPhone: "+8598 1565 8454",
    sellerPhoto: "https://i.ibb.co/m5BYp4z/profile-pic-3.png"
  },
  {
    id: 7,
    title: "Bugatti Veyron",
    description: "Vintage charm, aged elegance. Classic car with a rich history, a timeless ride of enduring beauty.",
    image: "https://i.ibb.co/ypWjTPQ/Bugatti-Veyron-Grand-Sport-Vitesse-World-Record-Edition-Front-Three-Quarters.jpg",
    price: 15000,
    totalRun: 98761,
    fuelType: "Gasoline",
    transmissionType: "Automatic",
    sellerName: "Mark Hub",
    sellerPhone: "+8598 1565 8454",
    sellerPhoto: "https://i.ibb.co/TTck0Hc/profile-square-extra-small.png"
  },
  {
    id: 8,
    title: "Bugatti Chiron",
    description: "The car is in super fresh condition.",
    image: "https://i.ibb.co/0V6H8gx/07-chiron-dynamic-34-front-web-1499959186.jpg",
    price: 9500,
    totalRun: 78965,
    fuelType: "Diesel",
    transmissionType: "Automatic",
    sellerName: "Mark Hub",
    sellerPhone: "+8598 1565 8454",
    sellerPhoto: "https://i.ibb.co/TTck0Hc/profile-square-extra-small.png"
  },
  
  {
    id: 9,
    title: "Toyota Camry",
    description: "A reliable and fuel-efficient sedan, perfect for daily commutes.",
    image: "https://i.ibb.co/tXWnWY8/ford-mustang.png",
    price: 22000,
    totalRun: 120000,
    fuelType: "Gasoline",
    transmissionType: "Automatic",
    sellerName: "Alice Cooper",
    sellerPhone: "+1 (123) 456-7890",
    sellerPhoto: "https://i.ibb.co/g4YtpzM/3.png"
  },
  {
    id: 10,
    title: "Honda Accord",
    description: "The Honda Accord is a midsize car known for its spacious interior and strong performance.",
    image: "https://i.ibb.co/R9JkqW3/audi-a3.png",
    price: 24000,
    totalRun: 90000,
    fuelType: "Gasoline",
    transmissionType: "Automatic",
    sellerName: "John Doe",
    sellerPhone: "+1 (234) 567-8901",
    sellerPhoto: "https://i.ibb.co/DWJy4Y9/3.png"
  },
  {
    id: 11,
    title: "Nissan Altima",
    description: "A comfortable and sporty sedan that offers excellent fuel economy.",
    image: "https://i.ibb.co/ZBJB87W/ford-f-150.png",
    price: 20000,
    totalRun: 70000,
    fuelType: "Gasoline",
    transmissionType: "Automatic",
    sellerName: "Jane Smith",
    sellerPhone: "+1 (345) 678-9012",
    sellerPhoto: "https://i.ibb.co/g4YtpzM/3.png"
  },
  {
    id: 12,
    title: "Ford Mustang",
    description: "A classic American muscle car known for its powerful performance and iconic design.",
    image: "https://i.ibb.co/bXvVyXv/audi-a6.png",
    price: 35000,
    totalRun: 45000,
    fuelType: "Gasoline",
    transmissionType: "Manual",
    sellerName: "Emily White",
    sellerPhone: "+1 (456) 789-0123",
    sellerPhoto: "https://i.ibb.co/DWJy4Y9/3.png"
  },
  
];

  